services:
  caddy:
    container_name: caddy
    image: docker.io/caddy:alpine
    restart: unless-stopped
    networks:
      podnet:
        ipv4_address: 10.89.0.6
    ports:
      - "80:80"
      - '443:443'
      - '9123:9123'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy/data:/data
      - ./caddy/config:/config

  actual-server:
    image: docker.io/actualbudget/actual-server:latest
    container_name: actual_server
    restart: unless-stopped
    networks:
      podnet:
        ipv4_address: 10.89.0.23
    ports:
      - '5006:5006'
    volumes:
      - $HOME/actualbudget/:/data

networks:
  podnet:
    driver: ipvlan
    ipam:
      config:
        - subnet: 10.89.0.0/24
        - range: 10.89.0.100/28
        - gateway: 10.89.0.1


